version: '3'
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"  # Map the PostgreSQL port to the host machine

